// The agent-facing instruction document served at GET /agent-skill.md
// (apps/daemon/src/api.ts). Compiled into the daemon binary as a plain
// string — no filesystem read — so it ships identically whether the daemon
// runs from source, from the pid-dashboard bundle, or embedded in a desktop
// app: there is no packaging story to get wrong.
//
// This module is deliberately dependency-free (no imports at all): platform/
// is cross-cutting infra shared across slices, and a doc string has nothing
// to import. The vocabulary and constants quoted below are checked against
// their real source of truth by the co-located drift guard, agent-skill.test.ts
// — that file, not this one, imports the daemon's actual named-key list,
// state-slug list, wait constants and route table, so this document cannot
// silently rot out of sync with the code it describes.
export const AGENT_SKILL_MD: string = [
  "# pi-browser-dashboard: agent skill",
  "",
  "You are an agent working inside a session that pi-browser-dashboard's daemon",
  "is mirroring, and you want to orchestrate other sessions from a shell: spawn",
  "helpers, watch them work, answer their prompts, collect results. This",
  "document is served by the daemon itself at `GET /agent-skill.md`, so it is",
  "always the authority on the surface the *running* daemon actually exposes.",
  "",
  "## What this is",
  "",
  "The daemon is a thin file-watcher and HTTP mirror over the Claude Code",
  "supervisor (the process behind `claude agents`). It does not run your",
  "sessions: the supervisor spawns them, gives them worktrees, and decides when",
  "they restart. The daemon only watches `~/.claude/daemon/roster.json` and",
  "each session's `~/.claude/jobs/<short>/state.json`, and republishes what it",
  "sees over HTTP and SSE.",
  "",
  "The one thing to internalize before anything else: you observe sessions",
  "through this daemon, you do not command them. There is no RPC that tells a",
  "session what to think or forces it into a state. `send`/`keys` type",
  "keystrokes into the same terminal a human would use; `wait`/`explain` read",
  "state the supervisor already wrote. If a session is not doing what you",
  "expect, the fix is `explain`, not a retry loop.",
  "",
  "## Finding this daemon",
  "",
  "You do not have to guess a port, and you do not have to hunt for the CLI.",
  "Every session this daemon spawns is given these:",
  "",
  "| variable | what it holds |",
  "|---|---|",
  "| `PID_URL` | the daemon's root url — the same value `pid --url` takes |",
  "| `PID_SKILL_URL` | the url of THIS document, correct for however this daemon serves its API |",
  "| `PID_BIN` | absolute path to a runnable `pid`, or unset if this install could not resolve one |",
  "",
  "```bash",
  'curl -s "$PID_SKILL_URL"        # this document, from inside the session',
  '"$PID_BIN" sessions             # the CLI, without needing it on PATH',
  "```",
  "",
  'Run `pid` through `"$PID_BIN"`. The bare name is on PATH in a pi pane (the',
  "daemon builds that pane's environment itself) but NOT in a claude background",
  "session: the supervisor claims a pre-warmed process whose environment predates",
  "your dispatch, so these variables reach you as session settings, which cannot",
  "extend PATH without overwriting it. If you want the bare name anyway, put it",
  "there yourself, once, at the top of your shell work:",
  "",
  "```bash",
  'export PATH="$(dirname "$PID_BIN"):$PATH"',
  "```",
  "",
  "If none of the variables are set, you are in a session this daemon did not",
  "spawn (a human started it, or the daemon booted after it did). Fall back to",
  "`pid --url http://localhost:8787`, or ask whoever spawned you.",
  "",
  "## Two ways in",
  "",
  "`pid`, the agent-facing CLI, is preferred: you are almost always composing",
  'it inside a shell (`pid wait ab12 --until done && pid send cd34 "next"`), so',
  "its exit code IS the result — no JSON body to parse to find out what",
  "happened.",
  "",
  "```",
  "pid sessions [--state <slug,...>] [--json]",
  "pid explain <short> [--json]",
  "pid wait <short> [--until <slug,...>] [--until-output <text> [--anchor <where>]]",
  "         [--via supervisor|screen|either] [--timeout <ms>] [--json]",
  "pid send <short> <text...> [--wait <slug,...>] [--timeout <ms>] [--json]",
  "pid keys <short> <name...> [--wait <slug,...>] [--timeout <ms>] [--json]",
  "pid spawn <intent> [--n <count>] [--agent <name>] [--cwd <path>] [--wait <slug,...>] [--json]",
  "pid stop <short>",
  "pid rm <short>",
  "```",
  "",
  "Base URL, in order: the `--url <base>` flag, then the `PID_URL` environment",
  "variable, then the default `http://localhost:8787`. `pid` probes",
  "`GET /health` at that URL: if it answers, requests go to the bare root (the",
  "dev daemon's layout); if it does not, `pid` assumes the single-port",
  "`pid-dashboard` layout and prefixes every request with `/__api` (SSE at",
  "`/events` stays unprefixed either way). You don't need to think about this —",
  "it's the same resolution `pid` already does for you — but it matters if you",
  "call the HTTP surface directly instead.",
  "",
  "The HTTP endpoints underneath are there for anything `pid` does not wrap, or",
  "for a caller that isn't a POSIX shell:",
  "",
  "- `GET /health` — liveness probe.",
  "- `GET /sessions` — every mirrored session (claude and pi).",
  "- `GET /sessions/:id` — one session's full mirrored state.",
  "- `GET /sessions/:id/explain` — state provenance; see Explain below.",
  "- `POST /sessions/:id/send` — raw keystrokes.",
  "- `POST /sessions/:id/keys` — named keystrokes; see Send and keys below.",
  "- `POST /sessions/:id/wait` — block on a state; see Wait below.",
  "- `POST /sessions/:id/stop` — end a session the supported way.",
  "- `POST /sessions/:id/rm` — remove a session's entry.",
  "- `POST /dispatch` — start a new session; see Spawn below.",
  "- `GET /events` — one SSE stream of every state change; poll",
  "  `GET /sessions` instead if you'd rather not hold a connection open.",
  "- `GET /agent-skill.md` — this document.",
  "",
  "## Session states",
  "",
  "Every session's `state` field is one of the slugs the supervisor reports, or",
  "the daemon's own catch-all for one it doesn't recognize:",
  "",
  "| slug | meaning |",
  "|---|---|",
  "| `done` | the task finished |",
  "| `working` | actively running |",
  "| `blocked` | waiting on you: a permission prompt or an AskUserQuestion menu |",
  "| `needs_input` | the same condition as blocked; older supervisor CLI versions use this spelling instead |",
  "| `idle` | finished its turn, ready for the next prompt |",
  "| `failed` | ended in error |",
  "| `stopped` | ended by claude stop / pid stop |",
  "| `unknown` | the supervisor sent a slug this daemon does not recognize |",
  "",
  "Treat blocked and needs_input as one condition when deciding whether a",
  "session needs you — they are the same wait, spelled two ways across",
  "supervisor versions. unknown is not a state the supervisor names on purpose:",
  "it is what a raw slug becomes when it matches none of the seven above (a",
  "supervisor upgrade, a typo, a state this daemon build predates). When you",
  "see it, `GET /sessions/:id/explain`'s `degradedFrom` field carries the raw",
  "value the supervisor actually sent, so you can tell a genuine surprise from",
  "a cosmetic rename.",
  "",
  "## Wait: block on a state instead of polling",
  "",
  "`POST /sessions/:id/wait` (`pid wait <short> --until <slug,...>`)",
  "subscribes to the daemon's event stream and returns as soon as the session",
  "reaches one of the states you name, instead of you polling `GET /sessions`",
  "in a loop.",
  "",
  '- Body: `{ "until": ["done", "failed"], "timeoutMs"?, "via"?, "untilOutput"? }`.',
  "  `until` is a list drawn from the slugs above; `timeoutMs` defaults to 30000",
  "  (30s) and is capped at 600000 (10 minutes) — the daemon rejects anything",
  "  larger with a 400, it does not silently clamp it. A wait needs `until` or",
  "  `untilOutput` (see below); one with neither is a 400 rather than a request",
  "  that blocks until it times out.",
  "- A wait is pinned to the occupant: at the moment you call it, the daemon",
  "  records who currently holds that short (its `sessionId`). If a different",
  "  session takes over the same short while you wait — the previous one was",
  "  stopped and something new started in its place — you get",
  "  `occupant_changed`, never a false `Satisfied` for a session you didn't",
  '  mean. Treat that as "go re-resolve the short", not "retry the wait".',
  '- Non-satisfied outcomes, all `200 { "ok": false, "reason": ..., "short": ... }`:',
  "  - `timeout` — nothing in `until` happened before `timeoutMs` elapsed; the",
  "    session may still be working, just slower than you budgeted.",
  "  - `occupant_changed` — see above; whoever you were watching is gone.",
  "  - `removed` — the session itself was deleted (`claude rm` / `pid rm`)",
  "    while you waited.",
  '- A short the daemon has never heard of is a `404 { "error": "not_found" }`,',
  "  not a wait outcome.",
  "",
  "### Which observation settles it",
  "",
  "There are two independent readings of what a session is doing, and `via`",
  "picks which one your wait trusts. The supervisor's reading is whatever its",
  "own status file last said. The screen's reading is a classification of the",
  "terminal itself — the daemon dumps every unattended pane every few seconds",
  "and matches what is drawn there (a live spinner, an unanswered permission",
  "prompt, an empty prompt line).",
  "",
  "| value | what may settle the wait |",
  "|---|---|",
  "| `supervisor` | the status file only. The default, and what a wait has always meant. |",
  "| `screen` | the classified terminal only. Use it when the status file is not to be trusted — a session that claims to be running but has not written anything for hours. |",
  "| `either` | whichever lands first. |",
  "",
  "- The satisfied payload names the winner: `{ ok: true, state, via, waitedMs }`",
  "  where `via` is `supervisor` or `screen` (never `either` — that is a",
  "  request, not an answer). A screen-satisfied wait is a weaker claim than a",
  "  supervisor-satisfied one: it says the pane looks like that state, not that",
  "  the agent reported it.",
  "- The screen can only ever report the three states it can see: working,",
  "  blocked and idle. A wait for done, failed or stopped cannot be satisfied by",
  "  the screen, so `via` screen with only those in `until` will always time out",
  "  — use `either` if you want the screen as a second chance rather than the",
  "  only one.",
  "- An unclassifiable screen never satisfies anything. No matcher firing is the",
  "  absence of evidence, not evidence of an idle pane.",
  "- The current screen counts, not just the next change: a pane already sitting",
  "  at an unanswered prompt satisfies a `blocked` wait immediately instead of",
  "  making you wait for a transition that already happened.",
  "- **Every pane of the session is read, not just the first one.** A zellij",
  "  session can hold several terminal panes, and the reading a wait settles on is",
  "  the most attention-worthy of them: blocked beats working, working beats idle,",
  "  and idle beats an unclassifiable screen. So a prompt waiting in a second pane",
  "  satisfies a `blocked` wait even while another pane is still generating — and,",
  "  the other way round, a session does NOT read as idle just because one of its",
  "  panes is resting at a shell.",
  "- The panes are addressable in their own right: while a session has more than",
  "  one, `pid terminals` lists each as `<scope>:<id>#<paneId>` (for example",
  "  `session:ab12#terminal_1`) beside the session's own row, and every row names",
  "  the pane its reading came off. Use those rows when a session-level `blocked`",
  "  leaves you asking WHICH pane is waiting.",
  "- `removed` still settles a wait under every `via` — a deleted session is not",
  "  an observation about state, it is the end of the thing being observed.",
  "- From the CLI: `pid wait ab12 --until idle --via screen`. It prints the",
  '  winner too — `ab12 reached "idle" via screen after 1234ms` — so a screen',
  "  answer is never mistaken for a supervisor-confirmed one.",
  "",
  "### Wait for output instead of a state",
  "",
  "`untilOutput` waits for text to appear on the session's screen — the analogue",
  "of watching a pane yourself. Use it when the thing you are waiting for has no",
  "state slug: a specific prompt, a test summary line, a banner your own tooling",
  "prints.",
  "",
  '- `{ "untilOutput": "Do you want to proceed?" }` — the shorthand: this',
  "  substring, anywhere on the screen.",
  '- `{ "untilOutput": { "text": "...", "anchor": "line" } }` — the explicit form.',
  "  Anchors are `anywhere` (default), `line-start`, `line-end` and `line`; the",
  "  anchored ones compare against the line with surrounding whitespace trimmed,",
  "  so they still fire on a real screen (a dump pads lines out to the viewport",
  "  width).",
  "- **The pattern is a literal, never a regex.** Every metacharacter is just a",
  "  character: `(a+)+$` matches those six characters. This is deliberate — a",
  "  caller-supplied regex evaluated inside the daemon's event path is a",
  "  denial-of-service surface with no way to time-bound it — so reach for an",
  "  anchor rather than expecting pattern syntax. Text is capped at 200",
  "  characters.",
  "- Satisfied looks different from a state wait, because there is no state to",
  '  report: `{ "ok": true, "short": ..., "matched": "<the line it appeared on>",',
  '  "waitedMs": ... }`. A state wait returns `state`/`via` instead, so check',
  "  which field is present.",
  "- `until` and `untilOutput` may be combined, and then it is whichever happens",
  '  first — "wait for the prompt, or for the session to die" is one wait, not two.',
  "  The reply tells you which fired.",
  "- Matching runs off the daemon's screen poller, so worst-case latency is one",
  "  poll interval (a few seconds), and only text still visible on screen can",
  "  match — this watches the pane, it does not tail a log. On a daemon with the",
  '  poller disabled you get `409 { "error": "screen_polling_disabled" }` rather',
  "  than a wait that could never succeed.",
  '- From the CLI: `pid wait ab12 --until-output "42 passed" --anchor line-end`.',
  "  A match prints the line it appeared on. The disabled-poller case is exit 8,",
  "  deliberately not the timeout code 3: retrying cannot fix a daemon setting,",
  "  so treat 8 as stop-and-report rather than try-again.",
  "",
  "## What the screen classifier reports",
  "",
  "The screen reading `via screen` trusts, the `terminal` object on explain, and",
  "`GET /terminal/states` are all the same thing: the daemon dumps every",
  "unattended pane on a timer, runs an ordered table of matchers over the text,",
  "and reports the first row that fires. Four readings exist, and they are a",
  "strict subset of the session states above — a pane at a resting prompt looks",
  "identical whether the session finished, failed or was stopped, so the",
  "classifier never claims to know which:",
  "",
  "| reading | what was on the screen |",
  "|---|---|",
  "| `working` | a live spinner, or a dispatched tool still pending |",
  "| `blocked` | an unanswered dialog: the session is waiting on a human |",
  "| `idle` | a finished turn, or an empty prompt line |",
  "| `unknown` | no matcher fired — the absence of evidence, not evidence of an idle pane |",
  "",
  "Every classification also names the row that produced it, and the line it",
  "matched. The row name matters when you want to distinguish two screens that",
  "read as the same state: `blocked` covers both dialogs below, and they take",
  "different answers.",
  "",
  "| matcher | what it recognizes | reads as |",
  "|---|---|---|",
  "| `permission-prompt` | a tool-permission dialog, header plus its numbered option list | blocked |",
  "| `permission-prompt-reject-option` | the same dialog seen by its reject option, for the variant that renders one | blocked |",
  "| `workspace-trust-prompt` | the do-you-trust-this-folder dialog a fresh directory asks before running anything | blocked |",
  "| `tool-call-waiting` | the pending marker a dispatched tool leaves until it returns | working |",
  "| `thinking-gerund` | the claude status line: an invented gerund plus an elapsed time | working |",
  "| `pi-working` | pi's spinner and its own working line | working |",
  "| `turn-complete` | the past-tense completion line printed when control returns to the prompt | idle |",
  "| `prompt-resting` | an empty prompt line and nothing else matched | idle |",
  "",
  "Order is priority: the blocked rows are tried before the working ones (a",
  "pending tool marker is still on screen while a dialog holds the tool up), and",
  "`prompt-resting` is last because the prompt box is drawn during a turn too.",
  "",
  "## Send and keys",
  "",
  "`POST /sessions/:id/send` takes a raw `keys` string — anything you could",
  "type — and writes it to the session's terminal. `POST /sessions/:id/keys`",
  "(`pid keys <short> <name...>`) is the named, safe subset of the same thing:",
  "instead of hand-encoding escape sequences, you name what you want to press.",
  "",
  "| name | keystroke |",
  "|---|---|",
  "| `escape` | Esc |",
  "| `enter` | Enter |",
  "| `tab` | Tab |",
  "| `shift-tab` | Shift+Tab |",
  "| `up` | Up arrow |",
  "| `down` | Down arrow |",
  "| `left` | Left arrow |",
  "| `right` | Right arrow |",
  "| `home` | Home |",
  "| `end` | End |",
  "| `page-up` | Page Up |",
  "| `page-down` | Page Down |",
  "| `backspace` | Backspace |",
  "| `delete` | Delete |",
  "| `space` | Space |",
  "",
  'Each step in the `sequence` array is either `{ "named": "<name>", "repeat"? }`',
  '(repeat an integer 1-32) or `{ "text": "<literal>" }` for ordinary text with',
  "no control characters — use `named` for those instead. Both endpoints accept",
  "the same optional `wait` object described above, applied after the keys go",
  "out.",
  "",
  "ctrl-z and ctrl-c are deliberately not in this vocabulary, and are rejected",
  "the same as any typo would be. ctrl-z is the exact byte the daemon's own",
  "attach pool uses to evict an idle `claude attach` — sending it yourself",
  "would silently detach the pooled session behind the daemon's back, and the",
  "next send would pay a fresh boot. ctrl-c quits the attached TUI outright;",
  "`POST /sessions/:id/stop` (`pid stop`) is the supported, observable way to",
  'end a session — a ctrl-c smuggled through as "just a keystroke" would end',
  "it invisibly.",
  "",
  "Recipe for answering an AskUserQuestion menu — move down twice, select, and",
  "confirm the session actually resumed:",
  "",
  "```bash",
  "pid keys ab12 down down enter --wait working,idle,blocked,needs_input",
  "```",
  "",
  "## Explain: when a state alone isn't enough",
  "",
  "`GET /sessions/:id/explain` (`pid explain <short>`) is the provenance",
  "surface. Reach for it when:",
  "",
  "- a card looks idle but you suspect it's actually stuck,",
  "- a session reports a state you didn't expect for the work you gave it,",
  "- a session that was updating a moment ago has simply stopped emitting",
  "  anything.",
  "",
  "Three fields matter most:",
  "",
  "- `stale` — true when the state is one of the three in-progress slugs",
  "  (working, blocked, needs_input) but state.json hasn't been touched in over",
  "  120000ms. A session that claims to be working and is stale probably isn't.",
  "- `pidAlive` — false means the worker process itself has died; the",
  "  supervisor respawns it on the next attach or peek, so this is",
  "  informational, not something you need to act on.",
  "- `screenDisagrees` — true when the classified terminal contradicts `state`.",
  "  This is the strongest signal on the endpoint, because it is two",
  "  independent observations of one session failing to match. `terminal`",
  "  carries the reading itself: `{ state, matcher, evidence, ageMs }` — which",
  "  rule fired, the exact line it matched, and how long ago the pane was",
  "  sampled — so you can check the claim rather than take it. Absent when",
  "  nothing has classified this session's pane yet.",
  "",
  "A resting pane is NOT a disagreement with a finished session: done, idle,",
  "stopped and failed all naturally sit at a prompt, so only the combinations",
  "that cannot both be true are reported — a session claiming to work whose",
  "pane is at rest, or one claiming to be blocked whose pane is still",
  "generating. An unclassifiable pane never disagrees with anything.",
  "",
  "### explain a pi session",
  "",
  "explain answers for pi runs too, and a pi run is where you need it most —",
  "because pi writes no per-session state.json at all. `source` reads",
  "`pi-spawn-log`: that state is not something pi reported, it is the daemon's",
  "own inference from two things it can see, the tail of pi's transcript and a",
  "probe of the pid it recorded at spawn. Read the `reasons` before you trust",
  "the slug. Three limits it will spell out for you:",
  "",
  "- `blocked` and `needs_input` are unreachable for a pi run. Nothing tells the",
  "  daemon pi is waiting on you, so a pi session sitting at a permission prompt",
  '  still reads "working" or "done". Only the screen can show one waiting.',
  "- `done` means pi's transcript ends with an assistant message — NOT that pi",
  "  exited. With `pidAlive: true` the run has not ended: it is resting at pi's",
  "  prompt, or mid-turn with a tool call in flight (the assistant's tool-use",
  "  message is the last entry until the result comes back). Do not read a pi",
  '  "done" as a finished run without checking `pidAlive` and the screen.',
  "- `stateFilePresent` is always false and `lastEventAgeMs` always absent for",
  "  pi: there is no status file to stat and the daemon keeps no event history",
  "  for a pi short. `stale` is measured against pi's transcript instead, or",
  "  against the spawn record when pi has not written a transcript yet.",
  "",
  "Consequence worth planning around: the screen classification is the only",
  "independent evidence a pi session has. With the poller off",
  "(`PID_TERMINAL_POLL_MS=0`) every field is one observer talking to itself, and",
  "explain says so rather than implying corroboration it does not have.",
  "",
  "## Automation: rules that react without you",
  "",
  "Everything above needs you to be there asking. A rules file lets the daemon",
  "react on its own: `<claudeConfigDir>/pid-dashboard/rules.json` pairs a",
  "condition with an action, and the engine watches both readings — a rule keys on",
  "`state` for the supervisor's or on `screen` for the classifier's. Screen rules",
  "are the ones that catch what nothing else can: an unanswered dialog, or a pane",
  "that went quiet while the status file still says it is working.",
  "",
  "```jsonc",
  "{",
  '  "enabled": true,                     // absent or false: the engine never evaluates anything',
  '  "rules": [{',
  '    "name": "page-me-on-an-unanswered-prompt",',
  '    "when": { "screen": "blocked", "matcher": "permission-prompt", "forMs": 120000 },',
  '    "do":   { "action": "notify", "message": "still waiting on a human" }',
  "  }]",
  "}",
  "```",
  "",
  "- `forMs` is the dwell: without it the rule fires the moment the screen enters",
  "  that reading, with it only once the reading has held that long. A prompt",
  "  answered in two seconds needs no rule; one nobody has touched for two",
  "  minutes does.",
  "- `matcher` narrows a reading to one row from the table above, so a rule about",
  "  a permission dialog is not also a rule about the folder-trust dialog. A name",
  "  outside that vocabulary is a validation error, not a rule that quietly never",
  "  fires. It cannot be combined with `unknown`, which by definition has no",
  "  matcher.",
  "- Actions are `notify`, `keys` and `stop`. A `keys` action needs `confirm: true`",
  "  on its own rule to ever be sent — there is no file-wide switch — because it",
  "  types into the same TUI a human may be watching.",
  "- Two loop breakers you cannot opt out of: a per-rule-per-session cooldown, and",
  "  a ceiling on total actions per session per window. A trip is reported as a",
  "  suppressed outcome in the firing log, never as silence.",
  "- `GET /rules` shows the parsed rules, validation errors and firing log;",
  "  `POST /rules/preview` evaluates every known session against the file and",
  "  reports what WOULD happen without firing anything; `POST /rules/pause` stops",
  "  actions at runtime without editing the file.",
  "",
  "**No rule ships enabled, and none answers a permission prompt for you.** The",
  "capability is there — a confirmed `keys` rule on `permission-prompt` will",
  "select an option — but approving a tool call on someone's behalf is a decision",
  "for whoever owns the machine, so it is theirs to write, not a default. If you",
  "were asked to set one up, say plainly which dialog it will answer and with",
  "which keystrokes.",
  "",
  "## Spawn: fan out and join",
  "",
  "`POST /dispatch` (`pid spawn <intent>`) starts a new session and returns its",
  "short. `pid spawn --n <count>` does this `count` times with the same intent",
  "and, with `--wait`, waits on every spawned short independently — fan-out and",
  "join in one command:",
  "",
  "```bash",
  "# Three independent attempts at the same task; wait for each to reach a",
  "# terminal state and print every outcome as JSON.",
  'pid spawn "run the flaky integration suite and report" \\',
  "  --n 3 --wait done,failed,stopped --json",
  "```",
  "",
  'Each element of the returned JSON array is `{ "short": "...", "wait": {...} }`;',
  "the process exit code is the worst outcome across all three attempts — see",
  "Exit codes below.",
  "",
  "When each worker needs a different intent, spawn them one at a time and wait",
  "on each short yourself:",
  "",
  "```bash",
  "a=$(pid spawn \"review the auth module\" --json | jq -r '.[0].short')",
  "b=$(pid spawn \"review the billing module\" --json | jq -r '.[0].short')",
  'pid wait "$a" --until done,failed,stopped',
  'pid wait "$b" --until done,failed,stopped',
  "```",
  "",
  "### Exit codes",
  "",
  "An orchestrating agent composes `pid` in a shell, so the exit code IS the",
  "API:",
  "",
  "| code | meaning |",
  "|---|---|",
  "| 0 | success / wait satisfied |",
  "| 1 | transport failure, 5xx, unreachable daemon, or a response this CLI's parser could not make sense of |",
  "| 2 | usage error (unknown command, missing argument, bad slug, unknown key name) — or an invalid recipe file / a cap-exceeded `pid fleet run` request |",
  "| 3 | wait timed out |",
  "| 4 | `occupant_changed` — the session was replaced under the wait |",
  "| 5 | `removed` — the session went away |",
  "| 6 | not found — the daemon returned 404, or `pid terminals <scope>:<id>` found no entry for that key |",
  "| 7 | `pid fleet run --wait`: the run finished with a failed or skipped step, or the daemon refused to start it because that fleet already has an active run |",
  "| 8 | `screen_polling_disabled` — `pid wait --until-output` against a daemon whose screen poller is off (`PID_TERMINAL_POLL_MS=0`), off its own `409`. Deterministic: retrying cannot help until the daemon is reconfigured, which is exactly why it is not 3 |",
  "",
  "## Honest limits",
  "",
  "An agent that trusts an oversold surface just wastes turns rediscovering the",
  "truth:",
  "",
  "- There is no official supervisor IPC. `send`/`keys` type into the same",
  "  `claude attach` TUI a human would use — they are keystrokes, not an API",
  "  the supervisor was designed to receive.",
  "- A pi session's state is inferred, never reported: pi writes no state.json,",
  "  so the daemon derives it from the transcript tail plus a pid probe. It can",
  "  therefore never say `blocked`/`needs_input` for a pi run, and its `done`",
  '  can mean "mid-tool-call". `GET /sessions/:id/explain` states these limits',
  "  in its `reasons` — read them instead of trusting a pi slug on its own.",
  "- A wait's `removed` outcome cannot be observed for a session addressed by",
  "  its `daemonShort` alias — the `session.removed` event carries the",
  "  underlying job-dir key, not the alias, so a wait pinned to the alias never",
  "  sees it and simply times out instead.",
  "- The daemon does not create worktrees, does not mint session ids, and does",
  "  not decide when a session restarts — all three are the supervisor's job.",
  "  Nothing here spawns or manages a worktree on your behalf.",
  "",
].join("\n")
