/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemeLabRouteImport } from './routes/theme-lab'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIdRouteImport } from './routes/sessions.$id'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'

const ThemeLabRoute = ThemeLabRouteImport.update({
  id: '/theme-lab',
  path: '/theme-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIdRoute = SessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/theme-lab': typeof ThemeLabRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/sessions/$id': typeof SessionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/theme-lab': typeof ThemeLabRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/sessions/$id': typeof SessionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/theme-lab': typeof ThemeLabRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/sessions/$id': typeof SessionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/theme-lab' | '/projects/$id' | '/sessions/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/theme-lab' | '/projects/$id' | '/sessions/$id'
  id: '__root__' | '/' | '/theme-lab' | '/projects/$id' | '/sessions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThemeLabRoute: typeof ThemeLabRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  SessionsIdRoute: typeof SessionsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theme-lab': {
      id: '/theme-lab'
      path: '/theme-lab'
      fullPath: '/theme-lab'
      preLoaderRoute: typeof ThemeLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$id': {
      id: '/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof SessionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThemeLabRoute: ThemeLabRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  SessionsIdRoute: SessionsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
