/**
 * Rendering a solved family into the six files that declare one — PURE.
 *
 * A theme family is not one edit, it is six, and they can disagree with each
 * other: the daisyUI tokens in `apps/web/tailwind.config.js`, the catalog entry
 * in `theme.core.ts`, the id list in `theme.core.test.ts`, the shape row in
 * `themeCatalog.test.ts`, and the two xterm palettes plus their lookup in
 * `terminalTheme.ts`. Miss one and the failure is somewhere else entirely — a
 * family with no shape row fails "carries the shape its family declares" with an
 * `undefined`, and a family with no palette silently inherits `pid`'s slate/sky
 * pane, which is the exact defect per-theme palettes were introduced to fix.
 *
 * So the insertion points live here as named anchors with a failure value each,
 * next to the templates they insert. Every `insert*` returns `{ value }` or
 * `{ error }` — a moved anchor stops the generator with the file and the shape it
 * was looking for, rather than writing something that fails a gate later.
 *
 * Pure by shape (`*.core.ts`): source text in, source text out. The reads and
 * writes are in `scripts/scaffold-theme.ts`.
 */
import {
  type FamilySpec,
  type Measurement,
  type Parsed,
  rgbOf,
  SHAPE_KEYS,
  type SolvedFamily,
  type SolvedVariant,
  type TerminalPalette,
  type ThemeTokens,
} from "./theme-solve.core"

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/

const key = (raw: string): string => (IDENTIFIER.test(raw) ? raw : `"${raw}"`)

const insertAt = (input: {
  readonly source: string
  readonly index: number
  readonly text: string
}): string => `${input.source.slice(0, input.index)}${input.text}${input.source.slice(input.index)}`

const missing = (input: { readonly file: string; readonly shape: string }): { error: string } => ({
  error: `${input.file}: anchor not found — expected ${input.shape}`,
})

// ── templates ───────────────────────────────────────────────────────────────

/** One entry of `tailwind.config.js`'s exported `THEMES` array. */
export const renderThemeObject = (input: { readonly tokens: ThemeTokens }): string => {
  const lines = Object.entries(input.tokens).map(([name, value]) => `    ${key(name)}: "${value}",`)
  return `  {\n${lines.join("\n")}\n  },\n`
}

export const renderThemesBlock = (input: { readonly family: SolvedFamily }): string =>
  [
    `  // ── ${input.family.spec.id} ${"─".repeat(Math.max(0, 68 - input.family.spec.id.length))}\n`,
    "  //\n",
    `  // Generated by \`bun run scaffold:theme\`. Every ink token below is the value\n`,
    `  // closest to maximum chroma that clears 4.5:1 on *this variant's* base-100,\n`,
    `  // and every base surface is one hue at three lightnesses. Retune by taste;\n`,
    `  // re-run the generator, or \`bun run theme:check\`, to keep the floors honest.\n`,
    renderThemeObject({ tokens: input.family.light.tokens }),
    renderThemeObject({ tokens: input.family.dark.tokens }),
  ].join("")

/** The `THEME_FAMILIES` row in `theme.core.ts`. */
export const renderCatalogEntry = (input: { readonly spec: FamilySpec }): string =>
  `  {\n    id: "${input.spec.id}",\n    label: "${input.spec.label}",\n    light: "${input.spec.id}light",\n    dark: "${input.spec.id}dark",\n  },\n`

/** The `SHAPE_BY_FAMILY` row in `themeCatalog.test.ts`. */
export const renderShapeRow = (input: { readonly spec: FamilySpec }): string => {
  const lines = SHAPE_KEYS.map((token) => `    "${token}": "${input.spec.shape[token]}",`)
  return `  ${input.spec.id}: {\n${lines.join("\n")}\n  },\n`
}

const paletteConstName = (input: {
  readonly id: string
  readonly variant: "Light" | "Dark"
}): string => `${input.id}${input.variant}`

/** One `const <id>Light: TerminalTheme = { … }` in `terminalTheme.ts`. */
const renderPaletteConst = (input: {
  readonly name: string
  readonly palette: TerminalPalette
}): string => {
  const lines = Object.entries(input.palette).map(([slot, value]) => `  ${slot}: "${value}",`)
  return `const ${input.name}: TerminalTheme = {\n${lines.join("\n")}\n}\n`
}

export const renderPalettesBlock = (input: { readonly family: SolvedFamily }): string => {
  const id = input.family.spec.id
  return [
    `// ── ${id} ${"─".repeat(Math.max(0, 72 - id.length))}\n`,
    "//\n",
    `// Generated. The pane is the per-channel midpoint of this theme's base-100 and\n`,
    `// base-200, which is what \`terminalTheme.test.ts\` requires of it; the cursor is\n`,
    `// the theme's own primary; every ink slot clears 3:1 on the pane, and all\n`,
    `// sixteen are declared in both variants because xterm's defaults assume a dark\n`,
    `// background. Give the family its character rule in the test file.\n`,
    renderPaletteConst({
      name: paletteConstName({ id, variant: "Light" }),
      palette: input.family.light.palette,
    }),
    "\n",
    renderPaletteConst({
      name: paletteConstName({ id, variant: "Dark" }),
      palette: input.family.dark.palette,
    }),
    "\n",
  ].join("")
}

export const renderPaletteMapEntries = (input: { readonly id: string }): string =>
  `  ${input.id}light: ${paletteConstName({ id: input.id, variant: "Light" })},\n  ${input.id}dark: ${paletteConstName({ id: input.id, variant: "Dark" })},\n`

// ── the generated character rule ────────────────────────────────────────────

const CHANNELS = ["r", "g", "b"] as const

const paneOrdering = (input: { readonly palette: TerminalPalette }): readonly string[] => {
  const [r = 0, g = 0, b = 0] = rgbOf({ hex: input.palette.background ?? "#000000" })
  const values: Readonly<Record<(typeof CHANNELS)[number], number>> = { r, g, b }
  const sorted = [...CHANNELS].sort((a, z) => values[z] - values[a])
  return sorted.slice(0, -1).flatMap((high, i) => {
    const low = sorted[i + 1]
    // Ties carry no ordering, so assert nothing rather than a comparison that
    // is false the moment a channel rounds the other way.
    return low === undefined || values[high] === values[low] ? [] : [`${high}>${low}`]
  })
}

/**
 * A family's character assertion, derived from the pane the solver produced.
 *
 * `apps/web/CLAUDE.md` is blunt about why this exists: "a family with no
 * character assertion can silently drift into a copy of another one; adding a
 * family means adding its rule". A channel *ordering* is the form the four
 * existing rules take — `candy`'s pane is magenta-leaning (red and blue over
 * green), `citrus`'s is strictly r > g > b — because "has some colour in it"
 * passes for `sunset` too.
 *
 * Generated from the output rather than from the design intent, so it starts as a
 * description. It only becomes a *claim* once someone replaces it with the
 * sentence the family is actually for — which the emitted comment says.
 */
export const renderCharacterTest = (input: { readonly family: SolvedFamily }): string => {
  const id = input.family.spec.id
  const variants: readonly SolvedVariant[] = [input.family.light, input.family.dark]
  const rules = variants.map((variant) => ({
    name: variant.name,
    order: paneOrdering({ palette: variant.palette }),
  }))
  const assertions = rules.flatMap(({ name, order }) =>
    order.map((pair) => {
      const [high = "r", low = "b"] = pair.split(">")
      return `      expect(pane("${name}").${high}, "${name}: pane lost its ${high}>${low} lean").toBeGreaterThan(\n        pane("${name}").${low},\n      )`
    }),
  )
  return `
  it("keeps the ${id} family's own pane, not a copy of another family's", () => {
    // GENERATED, and a description rather than a claim until you replace it with
    // the sentence this family is actually for. The existing rules are the model:
    // "candy's pane is magenta-leaning (red AND blue over green) — sunset is warm,
    // so its red beats its blue". A channel ordering is what makes two warm
    // families distinguishable by a test instead of by taste.
    const pane = (name: string) => at(terminalTheme({ theme: name }).background)
    {
${assertions.join("\n")}
    }
  })
`
}

// ── the measured report ─────────────────────────────────────────────────────

const ratioLine = (input: { readonly m: Measurement }): string =>
  `  ${input.m.ok ? "ok  " : "MISS"}  ${input.m.what.padEnd(30)} ${input.m.hex} on ${input.m.against}  ${input.m.ratio.toFixed(2)}:1 (floor ${input.m.floor})`

/**
 * The measurements, as a table.
 *
 * This is the artefact the ad-hoc versions of this solver produced and threw
 * away three times. Printing it is most of the value: "why is this hue bronze"
 * has an answer, and it is a number.
 */
export const renderReport = (input: {
  readonly family: SolvedFamily
  readonly verbose: boolean
}): string => {
  const shown = input.verbose
    ? input.family.measurements
    : input.family.measurements.filter((m) => !m.ok || !m.what.includes("ansi."))
  return [
    `${input.family.spec.id}: ${input.family.measurements.length} measurements, ${input.family.failures.length} miss`,
    ...shown.map((m) => ratioLine({ m })),
  ].join("\n")
}

// ── anchored insertion ──────────────────────────────────────────────────────

/** `tailwind.config.js` — before the `]` that closes the exported THEMES array. */
export const insertThemes = (input: {
  readonly source: string
  readonly block: string
}): Parsed<string> => {
  const options = input.source.indexOf("export const DAISYUI_OPTIONS")
  if (options < 0) {
    return missing({ file: "tailwind.config.js", shape: "`export const DAISYUI_OPTIONS`" })
  }
  const close = input.source.lastIndexOf("\n]\n", options)
  if (close < 0) {
    return missing({ file: "tailwind.config.js", shape: "the `]` closing `export const THEMES`" })
  }
  return { value: insertAt({ source: input.source, index: close + 1, text: input.block }) }
}

const closingBracketAfter = (input: {
  readonly source: string
  readonly declaration: string
  readonly bracket: string
}): number => {
  const start = input.source.indexOf(input.declaration)
  return start < 0 ? -1 : input.source.indexOf(input.bracket, start)
}

/** `theme.core.ts` — the last row of `THEME_FAMILIES`. Appending is the only safe edit. */
export const insertCatalogEntry = (input: {
  readonly source: string
  readonly entry: string
}): Parsed<string> => {
  const close = closingBracketAfter({
    source: input.source,
    declaration: "export const THEME_FAMILIES",
    bracket: "\n]\n",
  })
  if (close < 0) {
    return missing({ file: "theme.core.ts", shape: "`export const THEME_FAMILIES = [ … ]`" })
  }
  return { value: insertAt({ source: input.source, index: close + 1, text: input.entry }) }
}

/** `themeCatalog.test.ts` — the last row of `SHAPE_BY_FAMILY`. */
export const insertShapeRow = (input: {
  readonly source: string
  readonly row: string
}): Parsed<string> => {
  const close = closingBracketAfter({
    source: input.source,
    declaration: "const SHAPE_BY_FAMILY = {",
    bracket: "\n} as const",
  })
  if (close < 0) {
    return missing({
      file: "themeCatalog.test.ts",
      shape: "`const SHAPE_BY_FAMILY = { … } as const`",
    })
  }
  return { value: insertAt({ source: input.source, index: close + 1, text: input.row }) }
}

const PALETTES_DECL = "const PALETTES: Readonly<Record<string, TerminalTheme>> = {"

/** `terminalTheme.ts` — the two palette consts, then their two lookup rows. */
export const insertPalettes = (input: {
  readonly source: string
  readonly block: string
  readonly entries: string
}): Parsed<string> => {
  const decl = input.source.indexOf(PALETTES_DECL)
  if (decl < 0) return missing({ file: "terminalTheme.ts", shape: `\`${PALETTES_DECL}\`` })
  // Walk back over the comment block that introduces PALETTES so the generated
  // consts land above it rather than between the comment and the code it explains.
  const before = input.source.lastIndexOf("\n\n", decl)
  if (before < 0) return missing({ file: "terminalTheme.ts", shape: "a blank line above PALETTES" })
  const withConsts = insertAt({ source: input.source, index: before + 2, text: input.block })
  const close = closingBracketAfter({
    source: withConsts,
    declaration: PALETTES_DECL,
    bracket: "\n}\n",
  })
  if (close < 0) return missing({ file: "terminalTheme.ts", shape: "the `}` closing PALETTES" })
  return { value: insertAt({ source: withConsts, index: close + 1, text: input.entries }) }
}

/** `terminalTheme.test.ts` — inside the last describe, where the character rules live. */
export const insertCharacterTest = (input: {
  readonly source: string
  readonly block: string
}): Parsed<string> => {
  const close = input.source.lastIndexOf("\n})\n")
  if (close < 0) {
    return missing({
      file: "terminalTheme.test.ts",
      shape: "a top-level `describe(…)` to append to",
    })
  }
  return { value: insertAt({ source: input.source, index: close + 1, text: input.block }) }
}

const IDS_ARRAY = /expect\(ids\)\.toEqual\(\[([\s\S]*?)\]\)/

/** `theme.core.test.ts` — the literal id list the catalog is pinned against. */
export const insertFamilyId = (input: {
  readonly source: string
  readonly id: string
}): Parsed<string> => {
  const match = IDS_ARRAY.exec(input.source)
  if (match === null || match[1] === undefined) {
    return missing({ file: "theme.core.test.ts", shape: "`expect(ids).toEqual([ … ])`" })
  }
  const ids = [...match[1].matchAll(/"([a-z0-9-]+)"/g)].map((m) => m[1])
  if (ids.includes(input.id)) return { error: `theme.core.test.ts already lists "${input.id}"` }
  const rendered = [...ids, input.id].map((id) => `      "${id}",`).join("\n")
  return {
    value: input.source.replace(IDS_ARRAY, `expect(ids).toEqual([\n${rendered}\n    ])`),
  }
}

const COUNT_WORDS = [
  "zero",
  "one",
  "two",
  "three",
  "four",
  "five",
  "six",
  "seven",
  "eight",
  "nine",
  "ten",
  "eleven",
  "twelve",
  "thirteen",
  "fourteen",
  "fifteen",
  "sixteen",
  "seventeen",
  "eighteen",
  "nineteen",
  "twenty",
]

/**
 * "ships the nine sample families" -> "ships the ten sample families".
 *
 * Best-effort, and it returns a note rather than an error when it cannot: the
 * count is in a *test title*, which nothing asserts, so a stale word is a
 * documentation bug and not a red build. Worth doing anyway — every family so far
 * has left one of these behind, and #531 needed a follow-up commit for three.
 */
const countPhrase = (input: { readonly word: string }): string =>
  `the ${input.word} sample families`

const countWord = (input: { readonly count: number }): string => COUNT_WORDS[input.count] ?? ""

export const retitleFamilyCount = (input: {
  readonly source: string
  /**
   * How many daisyUI themes exist *before* this family — two per family, read off
   * `tailwind.config.js`.
   *
   * The arithmetic is in here rather than at the call site because the call site
   * got it wrong: passing the count of existing *families* looked right, left the
   * word one behind, and the generator reported "could not update" while the file
   * still said "nine" for ten families. A number the caller has to derive is a
   * number the caller can derive incorrectly, and no test could see it.
   */
  readonly themesBefore: number
}): { readonly text: string; readonly note: string | null } => {
  const count = input.themesBefore / 2 + 1
  const was = countWord({ count: count - 1 })
  const now = countWord({ count })
  const swappable = was !== "" && now !== "" && input.source.includes(countPhrase({ word: was }))
  return swappable
    ? {
        text: input.source.replaceAll(countPhrase({ word: was }), countPhrase({ word: now })),
        note: null,
      }
    : {
        text: input.source,
        note: "could not update the family count in theme.core.test.ts's title — say the new count by hand",
      }
}
